name: 'Nonprod Terraform Workflow'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  call-terraform-workflow:
    uses: ./.github/workflows/template-tf-plan-apply.yml
    with:
      environment: 'nonprod'
      tf_state_key: 'nonprod.tfstate'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
