name: 'Nonprod Terraform Workflow'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  call-terraform-workflow:
    uses: ./.github/workflows/template-tf-plan-apply.yml
    with:
      environment: 'nonproduction'
